/* =====================================================================
   GoodMonk Performance Command Center — Dashboard logic
   ---------------------------------------------------------------------
   Static site, no backend: reads JSON files generated by
   dashboard_data.py, renders everything client-side, and polls those
   same JSON files every 30s so the page updates without a reload.
   ===================================================================== */

const DATA_BASE = "data";
const REFRESH_MS = 30_000;

const state = {
  summary: null,
  pages: [],
  trends: { daily: [], weekly: [], monthly: [] },
  history: [],
  granularity: "daily",
  charts: {},
  rootCause: null, // Feature 1 addition — see fetchJSONOptional below
  journey: null,   // Feature 2 addition — see fetchJSONOptional below
  alerts: null,    // Feature 3 addition — see fetchJSONOptional below
  scheduler: null, // Feature 4 addition — see fetchJSONOptional below
};

// --- Data loading ---------------------------------------------------------

async function fetchJSON(path) {
  const res = await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status}`);
  return res.json();
}

// Feature 1 addition. Like fetchJSON, but never rejects — returns `fallback`
// on any failure (network error, 404, bad JSON) instead. Used only for the
// new, optional root_cause.json so that a missing/broken *new* file can
// never break the Promise.all() below and take down the existing,
// previously-working dashboard.
async function fetchJSONOptional(path, fallback) {
  try {
    return await fetchJSON(path);
  } catch (e) {
    console.warn(`Optional dashboard file "${path}" unavailable (non-fatal):`, e);
    return fallback;
  }
}

async function loadAll() {
  try {
    const [summary, pages, trends, history] = await Promise.all([
      fetchJSON("summary.json"),
      fetchJSON("pages.json"),
      fetchJSON("trends.json"),
      fetchJSON("history.json"),
    ]);
    state.summary = summary;
    state.pages = pages;
    state.trends = trends;
    state.history = history;

    // Feature 1 addition: loaded separately, after the required files
    // above have already succeeded, and never throws — the existing
    // dashboard sections always render even if this one is unavailable.
    state.rootCause = await fetchJSONOptional("root_cause.json", null);

    // Feature 2 addition: same pattern — journey.json may not exist yet
    // (e.g. right after this deploy, before the first journey-enabled run),
    // and must never block the rest of the dashboard from loading.
    state.journey = await fetchJSONOptional("journey.json", null);

    // Feature 3 addition: same pattern again — alerts.json may not exist
    // yet, and must never block the rest of the dashboard from loading.
    state.alerts = await fetchJSONOptional("alerts.json", null);

    // Feature 4 addition: same pattern again — scheduler.json may not
    // exist yet, and must never block the rest of the dashboard.
    state.scheduler = await fetchJSONOptional("scheduler.json", null);

    renderAll();
  } catch (e) {
    console.error("Dashboard data load failed:", e);
    document.getElementById("load-error").style.display = "block";
  }
}

// --- Rendering: vitals bar -------------------------------------------------

function overallStatusColor() {
  const s = state.summary;
  if (!s) return "grey";
  if (s.critical_count > 0) return "red";
  if (s.warning_count > 0) return "yellow";
  if (s.healthy_count > 0) return "green";
  return "grey";
}

function renderVitalsBar() {
  const s = state.summary || {};
  const color = overallStatusColor();

  document.getElementById("status-dot").className = `status-dot status-color-${color}`;
  document.getElementById("last-run").textContent = s.generated_at ? new Date(s.generated_at).toLocaleString() : "—";
  document.getElementById("next-run").textContent = s.next_scheduled_run ? new Date(s.next_scheduled_run).toLocaleString() : "—";
  document.getElementById("run-status").textContent = (s.last_run_status || "never_run").replace(/_/g, " ");

  const running = document.getElementById("running-count");
  running.textContent = state.pages.filter(p => p.status_color !== "grey").length + " / " + (s.total_urls ?? state.pages.length);

  updatePulse(color);
}

// --- Signature element: animated heartbeat/pulse line ----------------------

let pulsePhase = 0;
function updatePulse(color) {
  const svg = document.getElementById("pulse-svg");
  const path = document.getElementById("pulse-path");
  const colorVar = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" }[color];
  path.style.color = colorVar;

  // Build a heartbeat-monitor style waveform: flat line with periodic spikes.
  const width = 600, height = 40, mid = height / 2;
  const speed = { green: 1, yellow: 1.4, red: 1.9, grey: 0.4 }[color];
  let d = `M0,${mid}`;
  const segment = 60;
  for (let x = 0; x <= width; x += segment) {
    const beatOffset = (x / segment) % 1;
    d += ` L${x + segment * 0.35},${mid}`;
    d += ` L${x + segment * 0.42},${mid - 14}`;
    d += ` L${x + segment * 0.48},${mid + 10}`;
    d += ` L${x + segment * 0.54},${mid - 4}`;
    d += ` L${x + segment * 0.62},${mid}`;
  }
  path.setAttribute("d", d);
  svg.style.setProperty("--pulse-speed", `${3 / speed}s`);
}

// --- Rendering: KPI strip -------------------------------------------------

function renderKPIs() {
  const s = state.summary || {};
  const kpis = [
    { label: "Total URLs", value: s.total_urls ?? "—" },
    { label: "Average Score", value: s.average_score ?? "—" },
    { label: "Best Page", value: s.best_page ?? "—", sub: true },
    { label: "Worst Page", value: s.worst_page ?? "—", sub: true },
    { label: "Healthy", value: s.healthy_count ?? 0, color: "var(--accent-teal)" },
    { label: "Warning", value: s.warning_count ?? 0, color: "var(--accent-amber)" },
    { label: "Critical", value: s.critical_count ?? 0, color: "var(--accent-red)" },
    { label: "No Data Yet", value: s.no_data_count ?? 0, color: "var(--text-faint)" },
  ];
  const el = document.getElementById("kpi-strip");
  el.innerHTML = kpis.map(k => `
    <div class="kpi-card">
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value" style="${k.color ? `color:${k.color}` : ""}; ${k.sub ? "font-size:16px;" : ""}">${k.value}</div>
    </div>
  `).join("");
}

// --- Rendering: page vitals grid -------------------------------------------

function renderPagesGrid() {
  const el = document.getElementById("pages-grid");
  if (!state.pages.length) {
    el.innerHTML = `<div class="empty-state">No runs yet. The first scheduled run will populate this grid.</div>`;
    return;
  }
  el.innerHTML = state.pages.map(p => {
    const latest = p.latest || {};
    const color = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" }[p.status_color];
    return `
    <div class="page-card" style="color:${color}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${p.name}</div>
        <div class="pc-score" style="color:${color}">${latest["Performance Score"] ?? "—"}</div>
      </div>
      <div class="pc-metrics">
        <span>LCP ${latest["LCP"] ?? "—"}s</span>
        <span>Grade ${latest["Grade"] ?? "—"}</span>
      </div>
      <div class="pc-footer">
        <span>${p.total_runs} runs · ${p.failed_runs} failed</span>
        ${latest["Report URL"] ? `<a href="${latest["Report URL"]}" target="_blank" rel="noopener">Report ↗</a>` : ""}
      </div>
    </div>`;
  }).join("");
}

// --- Rendering: Root Cause cards (Feature 1 addition) -----------------------
// Fully new section. Does not read or modify any state used by the sections
// above/below it. No-ops cleanly (renders nothing) if root_cause.json isn't
// available yet — see fetchJSONOptional above.

function renderRootCauseCards() {
  const el = document.getElementById("root-cause-grid");
  if (!el) return; // defensive: section not present in an older cached index.html

  const pages = (state.rootCause && state.rootCause.pages) || [];
  const withIssues = pages.filter(p => p.latest_report && p.latest_report.issue_count > 0);

  if (!withIssues.length) {
    el.innerHTML = `<div class="empty-state">No root-cause issues detected in the latest run.</div>`;
    return;
  }

  const severityColor = { critical: "var(--accent-red)", warning: "var(--accent-amber)", info: "var(--accent-blue)" };

  el.innerHTML = withIssues
    .sort((a, b) => b.latest_report.issue_count - a.latest_report.issue_count)
    .map(p => {
      const report = p.latest_report;
      const topIssues = (report.issues || []).slice(0, 3);
      const issuesHtml = topIssues.map(i => `
        <div class="rc-issue" style="border-left:3px solid ${severityColor[i.severity] || 'var(--text-faint)'}">
          <div class="rc-issue-title">${i.title}</div>
          <div class="rc-issue-detail">${i.detail}</div>
        </div>`).join("");
      return `
      <div class="page-card">
        <div class="pc-head">
          <div class="pc-name" style="color:var(--text)">${p.name}</div>
          <div class="pc-score" style="color:var(--accent-red)">${report.issue_count} issue${report.issue_count === 1 ? "" : "s"}</div>
        </div>
        ${issuesHtml}
      </div>`;
    }).join("");
}

// --- Rendering: Customer Journey (Feature 2 addition) -----------------------
// Fully new section, same isolation pattern as renderRootCauseCards above:
// reads only state.journey, writes only to its own DOM nodes, no-ops
// cleanly if journey.json isn't available yet or the section isn't present
// in an older cached index.html.

function renderJourneyCards() {
  const el = document.getElementById("journey-grid");
  const rateEl = document.getElementById("journey-success-rate");
  if (!el) return;

  const products = (state.journey && state.journey.products) || [];

  if (rateEl) {
    const rate = state.journey && state.journey.overall_success_rate;
    rateEl.textContent = rate != null ? `${rate}%` : "—";
  }

  if (!products.length) {
    el.innerHTML = `<div class="empty-state">No journey runs yet. The first journey-enabled run will populate this section.</div>`;
    return;
  }

  el.innerHTML = products.map(p => {
    const ok = p.latest_status === "Success";
    const color = ok ? "var(--accent-teal)" : "var(--accent-red)";
    const timelineHtml = (p.timeline || []).slice(-20).map(t => `
      <span class="journey-dot" style="background:${t.success ? 'var(--accent-teal)' : 'var(--accent-red)'}" title="${t.date} ${t.time}"></span>
    `).join("");
    return `
    <div class="page-card" style="color:${color}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${p.product_name}</div>
        <div class="pc-score" style="color:${color}">${p.latest_status || "—"}</div>
      </div>
      <div class="pc-metrics">
        <span>${p.successful_runs}/${p.total_runs} runs OK</span>
        ${!ok && p.latest_failed_step ? `<span>Failed at: ${p.latest_failed_step}</span>` : ""}
      </div>
      <div class="journey-timeline">${timelineHtml}</div>
    </div>`;
  }).join("");
}

// --- Rendering: Alerts (Feature 3 addition) ---------------------------------
// Same isolation pattern as renderRootCauseCards/renderJourneyCards: reads
// only state.alerts, writes only to its own DOM nodes, no-ops cleanly if
// alerts.json isn't available yet or the section isn't present in an
// older cached index.html.

function renderAlertsSection() {
  const el = document.getElementById("alerts-grid");
  const countEl = document.getElementById("alert-active-count");
  if (!el) return;

  const data = state.alerts;
  const active = (data && data.active_alerts) || [];
  const recent = (data && data.recent_alerts) || [];

  if (countEl) countEl.textContent = data ? String(data.total_active ?? active.length) : "—";

  if (!recent.length) {
    el.innerHTML = `<div class="empty-state">No alerts yet. This section fills in once the alert engine has a run to evaluate.</div>`;
    return;
  }

  const severityColor = { critical: "var(--accent-red)", high: "var(--accent-amber)", warning: "var(--accent-amber)", info: "var(--accent-blue)" };

  el.innerHTML = recent.slice(0, 15).map(a => {
    const isRecovered = a["Status"] === "Recovered";
    const color = isRecovered ? "var(--accent-teal)" : (severityColor[(a["Severity"] || "warning").toLowerCase()] || "var(--text-faint)");
    const label = isRecovered ? "RECOVERED" : (a["Severity"] || "warning").toUpperCase();
    return `
    <div class="page-card" style="color:${color}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${a["Alert Type"] || ""}</div>
        <div class="pc-score" style="color:${color}">${label}</div>
      </div>
      <div class="pc-metrics">
        <span>${a["Affected Page"] || a["Module"] || ""}</span>
        <span>${a["Date"] || ""} ${a["Time"] || ""}</span>
      </div>
    </div>`;
  }).join("");
}

// --- Rendering: Scheduler (Feature 4 addition) ------------------------------
// Same isolation pattern as the sections above: reads only
// state.scheduler, writes only to its own DOM nodes, no-ops cleanly if
// scheduler.json isn't available yet or the section isn't present in an
// older cached index.html.

function renderSchedulerSection() {
  const el = document.getElementById("scheduler-grid");
  const nextRunEl = document.getElementById("scheduler-next-run");
  const lastSuccessEl = document.getElementById("scheduler-last-success");
  const healthEl = document.getElementById("scheduler-health");
  const queueEl = document.getElementById("scheduler-queue-count");
  if (!el) return;

  const data = state.scheduler;
  const pages = (data && data.pages) || [];

  if (nextRunEl) nextRunEl.textContent = data && data.next_scheduled_run_overall ? new Date(data.next_scheduled_run_overall).toLocaleString() : "—";
  if (lastSuccessEl) lastSuccessEl.textContent = data && data.last_successful_run_overall ? new Date(data.last_successful_run_overall).toLocaleString() : "—";
  if (healthEl) {
    const health = (data && data.scheduler_health) || "—";
    healthEl.textContent = health;
    healthEl.style.color = health === "critical" ? "var(--accent-red)" : "var(--accent-teal)";
  }
  if (queueEl) {
    const lastRun = data && data.last_run;
    queueEl.textContent = lastRun ? `${lastRun.pages_checked ?? "—"} checked / ${lastRun.pages_skipped ?? "—"} skipped` : "—";
  }

  if (!pages.length) {
    el.innerHTML = `<div class="empty-state">No scheduler data yet. This section fills in after the first scheduler-enabled run.</div>`;
    return;
  }

  el.innerHTML = pages.map(p => {
    const unhealthy = (p.failure_count || 0) >= 3;
    const color = unhealthy ? "var(--accent-red)" : (p.last_status === "success" ? "var(--accent-teal)" : "var(--text-faint)");
    return `
    <div class="page-card" style="color:${color}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${p.name}</div>
        <div class="pc-score" style="color:${color}">${p.priority} · ${p.interval_hours}h</div>
      </div>
      <div class="pc-metrics">
        <span>Last: ${p.last_run ? new Date(p.last_run).toLocaleTimeString() : "never"}</span>
        <span>Next: ${p.next_run ? new Date(p.next_run).toLocaleTimeString() : "—"}</span>
      </div>
      ${p.failure_count ? `<div class="pc-metrics"><span>Failures: ${p.failure_count}</span></div>` : ""}
    </div>`;
  }).join("");
}

// --- Rendering: trend charts (Chart.js) ------------------------------------

function chartTheme() {
  const styles = getComputedStyle(document.documentElement);
  return {
    text: styles.getPropertyValue("--text-muted").trim(),
    grid: styles.getPropertyValue("--hairline").trim(),
    teal: styles.getPropertyValue("--accent-teal").trim(),
    amber: styles.getPropertyValue("--accent-amber").trim(),
    blue: styles.getPropertyValue("--accent-blue").trim(),
  };
}

function buildLineChart(canvasId, labels, datasets) {
  const ctx = document.getElementById(canvasId).getContext("2d");
  if (state.charts[canvasId]) state.charts[canvasId].destroy();
  const theme = chartTheme();
  state.charts[canvasId] = new Chart(ctx, {
    type: "line",
    data: { labels, datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: "index", intersect: false },
      plugins: { legend: { labels: { color: theme.text, font: { family: "Inter", size: 11 } } } },
      scales: {
        x: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
        y: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
      },
      elements: { point: { radius: 2 }, line: { tension: 0.3 } },
    },
  });
}

function renderTrendCharts() {
  const theme = chartTheme();
  const series = state.trends[state.granularity] || [];
  const labels = series.map(s => s.period);

  buildLineChart("chart-score", labels, [{
    label: "Avg Score", data: series.map(s => s.avg_score),
    borderColor: theme.teal, backgroundColor: theme.teal + "33", fill: true,
  }]);
  buildLineChart("chart-lcp", labels, [{
    label: "Avg LCP (s)", data: series.map(s => s.avg_lcp),
    borderColor: theme.amber, backgroundColor: theme.amber + "33", fill: true,
  }]);
  buildLineChart("chart-load", labels, [{
    label: "Avg Fully Loaded (s)", data: series.map(s => s.avg_fully_loaded),
    borderColor: theme.blue, backgroundColor: theme.blue + "33", fill: true,
  }]);

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.granularity === state.granularity);
  });
}

// --- Rendering: history table with search/filter ----------------------------

function getFilteredHistory() {
  const q = document.getElementById("search-input").value.trim().toLowerCase();
  const statusFilter = document.getElementById("status-filter").value;
  return state.history.filter(r => {
    if (statusFilter !== "all" && r.Status !== statusFilter) return false;
    if (!q) return true;
    return (r._page_name || "").toLowerCase().includes(q) || (r._sheet_name || "").toLowerCase().includes(q);
  });
}

function renderHistoryTable() {
  const rows = getFilteredHistory().slice().reverse().slice(0, 500); // most recent first, capped for render speed
  const tbody = document.getElementById("history-tbody");

  if (!rows.length) {
    tbody.innerHTML = `<tr><td colspan="8" class="empty-state">No matching history rows.</td></tr>`;
    return;
  }

  tbody.innerHTML = rows.map(r => {
    const isOk = r.Status === "OK";
    const badgeColor = isOk ? "var(--accent-teal)" : "var(--accent-red)";
    return `
    <tr>
      <td>${r.Date || ""} ${r.Time || ""}</td>
      <td>${r._page_name || r._sheet_name || ""}</td>
      <td>${r["Performance Score"] ?? "—"}</td>
      <td>${r["Grade"] ?? "—"}</td>
      <td>${r["LCP"] ?? "—"}</td>
      <td>${r["Fully Loaded"] ?? "—"}</td>
      <td><span class="badge" style="background:${badgeColor}22;color:${badgeColor}">${r.Status || "—"}</span></td>
      <td>${r["Report URL"] ? `<a href="${r["Report URL"]}" target="_blank" rel="noopener">View</a>` : "—"}</td>
    </tr>`;
  }).join("");
}

// --- Export ------------------------------------------------------------------

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = ["Date", "Time", "_page_name", "Performance Score", "Grade", "LCP", "Onload", "Fully Loaded", "TTFB", "CLS", "TBT", "Report URL", "Status"];
  const lines = [headers.join(",")];
  rows.forEach(r => {
    lines.push(headers.map(h => `"${String(r[h] ?? "").replace(/"/g, '""')}"`).join(","));
  });
  return lines.join("\n");
}

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function exportCSV() {
  const rows = getFilteredHistory();
  downloadBlob(toCSV(rows), `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv");
}

function exportExcel() {
  // Excel opens well-formed CSV directly; avoids pulling in a full XLSX
  // library for a static dashboard. Renamed .xls with an HTML table is
  // the classic zero-dependency trick for real Excel formatting.
  const rows = getFilteredHistory();
  const headers = ["Date", "Time", "Page", "Score", "Grade", "LCP", "Fully Loaded", "Status", "Report URL"];
  let html = `<table><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr>`;
  rows.forEach(r => {
    html += `<tr><td>${r.Date || ""}</td><td>${r.Time || ""}</td><td>${r._page_name || ""}</td>` +
      `<td>${r["Performance Score"] ?? ""}</td><td>${r["Grade"] ?? ""}</td><td>${r["LCP"] ?? ""}</td>` +
      `<td>${r["Fully Loaded"] ?? ""}</td><td>${r["Status"] ?? ""}</td><td>${r["Report URL"] ?? ""}</td></tr>`;
  });
  html += "</table>";
  downloadBlob(html, `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.xls`, "application/vnd.ms-excel");
}

// --- Dark mode -----------------------------------------------------------

function initTheme() {
  const saved = localStorage.getItem("gm-theme") || "dark";
  document.documentElement.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").textContent = saved === "dark" ? "☀" : "☾";
}

function toggleTheme() {
  const current = document.documentElement.getAttribute("data-theme") || "dark";
  const next = current === "dark" ? "light" : "dark";
  document.documentElement.setAttribute("data-theme", next);
  localStorage.setItem("gm-theme", next);
  document.getElementById("theme-toggle").textContent = next === "dark" ? "☀" : "☾";
  renderTrendCharts(); // re-theme chart colors
}

// --- Wire-up ---------------------------------------------------------------

function renderAll() {
  renderVitalsBar();
  renderKPIs();
  renderPagesGrid();
  renderRootCauseCards(); // Feature 1 addition
  renderJourneyCards();   // Feature 2 addition
  renderAlertsSection();  // Feature 3 addition
  renderSchedulerSection(); // Feature 4 addition
  renderTrendCharts();
  renderHistoryTable();
  document.getElementById("load-error").style.display = "none";
}

function initControls() {
  document.getElementById("theme-toggle").addEventListener("click", toggleTheme);
  document.getElementById("search-input").addEventListener("input", renderHistoryTable);
  document.getElementById("status-filter").addEventListener("change", renderHistoryTable);
  document.getElementById("export-csv").addEventListener("click", exportCSV);
  document.getElementById("export-excel").addEventListener("click", exportExcel);
  document.getElementById("refresh-now").addEventListener("click", loadAll);

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.addEventListener("click", () => {
      state.granularity = btn.dataset.granularity;
      renderTrendCharts();
    });
  });
}

document.addEventListener("DOMContentLoaded", () => {
  initTheme();
  initControls();
  loadAll();
  setInterval(loadAll, REFRESH_MS);
});
